name: BerryBites CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and test
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: src/berrybites.ui
        run: npm ci
      - name: Build
        working-directory: src/berrybites.ui
        run: npm run build
      - name: Test
        working-directory: src/berrybites.ui
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          output_location: /dist
          app_location: /src/berrybites.ui
      - name: Adjust permissions
        run: sudo chown -R $(whoami):$(whoami) .git/
